---
- name: Load operating-system specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

# Required for direct install of parallel package from linuxsoft.cern.ch
- rpm_key:
    state: present
    key: https://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install LF Recommended Tools on RedHat
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install LF Recommended Tools on Debian
  # Note: apt module requires state: 'fixed' not in dnf or yum modules
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: fixed
  when: ansible_os_family == 'Debian'
  become: true

- name: Install fedora-packager
  yum: name=fedora-packager state=present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install PlantUML
  block:
    - name: Create /opt/plantuml install directory
      file:
        path: /opt/plantuml
        state: directory
        mode: 0755
    - name: Fetch PlantUML
      get_url:
        url: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        dest: /opt/plantuml/plantuml.jar
        mode: 0644
      register: result
      until: result is succeeded
      retries: 3
      delay: 30
    - name: Install PlantUML executable script
      copy:
        content: |
          #!/bin/sh
          exec java -jar /opt/plantuml/plantuml.jar "$@"
        dest: /usr/local/bin/plantuml
        mode: 0755
  become: true
