---
- name: Load operating-system specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"

- name: Setup Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Install LF Recommended Tools
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: present
  become: true

- name: Install fedora-packager
  yum: name=fedora-packager state=present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install list of gem packages
  gem: name={{ item }} state=latest
  with_items:
       - rake
       - package_cloud
  become: true

- name: Install PlantUML
  block:
    - name: Create /opt/plantuml install directory
      file:
        path: /opt/plantuml
        state: directory
        mode: 0755
    - name: Fetch PlantUML
      get_url:
        url: http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        dest: /opt/plantuml/plantuml.jar
        mode: 0644
    - name: Install PlantUML executable script
      copy:
        content: |
          #!/bin/sh
          exec java -jar /opt/plantuml/plantuml.jar "$@"
        dest: /usr/local/bin/plantuml
        mode: 0755
  become: true
