---
- name: Load operating-system specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"

- name: Setup Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Install LF Recommended Tools
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: present
  become: true

- name: Install fedora-packager
  yum: name=fedora-packager state=present
  when: ansible_os_family == 'RedHat'
  become: true
