---
- name: Load operating-system specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: Setup Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
  # Ubuntu 20.04 PPA is not yet available so skip installing it for now.
  # TODO: Figure out if recent versions of Ansible in Ubuntu is sufficient for
  #.      our use without the need to pull in from PPA.
  when: ansible_distribution == 'Ubuntu' and ansible_facts['distribution_major_version'] is version('20', '<')
  become: true

- name: Install LF Recommended Tools
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: present
  become: true

- name: Install fedora-packager
  yum: name=fedora-packager state=present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install PlantUML
  block:
    - name: Create /opt/plantuml install directory
      file:
        path: /opt/plantuml
        state: directory
        mode: 0755
    - name: Fetch PlantUML
      get_url:
        url: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        dest: /opt/plantuml/plantuml.jar
        mode: 0644
      register: result
      until: result is succeeded
      retries: 3
      delay: 30
    - name: Install PlantUML executable script
      copy:
        content: |
          #!/bin/sh
          exec java -jar /opt/plantuml/plantuml.jar "$@"
        dest: /usr/local/bin/plantuml
        mode: 0755
  become: true
