---
- name: Load operating-system specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

# Required for direct install of parallel package from linuxsoft.cern.ch
- name: Install RPM GPG certs
  ansible.builtin.rpm_key:
    state: present
    key: https://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install LF Recommended Tools on RedHat
  ansible.builtin.yum:
    name: "{{ lf_recommended_tools_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install pre-packages on Debian
  # These packages must be installed before others
  ansible.builtin.package:
    name:
      - apt-utils
      - pcp
    state: present
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_distribution_major_version | int >= 24
  become: true

- name: Install LF Recommended Tools on Debian
  # Note: apt module requires state: 'fixed' not in dnf or yum modules
  ansible.builtin.package:
    name: "{{ lf_recommended_tools_packages }}"
    state: fixed
  when: ansible_os_family == 'Debian'
  become: true

- name: Install fedora-packager
  ansible.builtin.yum:
    name:
      - fedora-packager
    state: present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install PlantUML
  become: true
  block:
    - name: Create /opt/plantuml install directory
      ansible.builtin.file:
        path: /opt/plantuml
        state: directory
        mode: 0755
    - name: Fetch PlantUML
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        validate_certs: false
        dest: /opt/plantuml/plantuml.jar
        mode: 0644
      register: result
      until: result is succeeded
      retries: 3
      delay: 30
    - name: Install PlantUML executable script
      ansible.builtin.copy:
        content: |
          #!/bin/sh
          exec java -jar /opt/plantuml/plantuml.jar "$@"
        dest: /usr/local/bin/plantuml
        mode: 0755

- name: Add NodeSource repository/NodeJS
  vars:
    # Sets the packaged/baseline version of NodeJS
    nodejs_version: "22.x"
  block:
    - name: Add NodeSource repository/NodeJS under RedHat/CentOS
      become: true
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Set up the Nodesource RPM directory.
          ansible.builtin.set_fact:
            nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"

        - name: Import Nodesource RPM key
          ansible.builtin.rpm_key:
            key:
              https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
            state: present

        - name: Add Nodesource repositories for Node.js (CentOS 7+).
          ansible.builtin.yum:
            name:
              "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/\
              {{ ansible_distribution_major_version }}/\
              {{ ansible_architecture }}/nodesource-release-el\
              {{ ansible_distribution_major_version }}-1.noarch.rpm"
            state: present
          when: ansible_distribution_major_version | int >= 7
          register: node_repo

        - name: Update package cache if repo was added.
          ansible.builtin.yum: update_cache=yes
          when: node_repo is changed
          tags: ["skip_ansible_lint"]

        - name: Ensure Node.js AppStream module is disabled (CentOS 8+).
          ansible.builtin.command: yum module disable -y nodejs  # noqa command-instead-of-module
          register: module_disable
          changed_when: "'Nothing to do.' not in module_disable.stdout"
          when: ansible_distribution_major_version | int >= 8

        - name: Ensure Node.js and npm are installed.
          ansible.builtin.yum:
            name: "nodejs-{{ nodejs_version | regex_replace('x', '') }}*"
            state: present

    - name: Add NodeSource repository/NodeJS under Ubuntu
      become: true
      when: ansible_facts['distribution'] == 'Ubuntu'
      block:
        - name: Import the NodeSource GPG key into apt
          ansible.builtin.apt_key:
            url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
            state: present

        - name: Add NodeSource deb repository
          ansible.builtin.apt_repository:
            repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} \
                   nodistro main"
            state: present

        - name: Add NodeSource deb-src repository
          ansible.builtin.apt_repository:
            repo: "deb-src \
                   https://deb.nodesource.com/node_{{ nodejs_version }} \
                   nodistro main"
            state: present

        - name: Install Node.js
          ansible.builtin.package:
            pkg:
              - nodejs
            state: present
            update_cache: true
