---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint -v tasks/* vars/*
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntu1604
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
