---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/default/converge.yml
  flake8
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntu1604
    image: ubuntu:16.04
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
