---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Update APT cache
      ansible.builtin.package:
        update_cache: true
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true

    - name: Install EPEL for CentOS/RHEL 9+
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] is version('9', '>=')
      become: true

    - name: Install EPEL for CentOS/RHEL 8
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
        state: present
        disable_gpg_check: true
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      become: true

    - name: Replace curl-minimal with curl on CentOS 9+
      ansible.builtin.shell: |
        dnf remove -y curl-minimal && dnf install -y curl
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] is version('9', '>=')
      become: true
      changed_when: true
